# This file is part of twikiget.
# Copyright (C) 2019 CERN.
#
# twikiget is free software; you can redistribute it and/or modify it
# under the terms of the MIT License; see LICENSE file for more details.

notifications:
  email: false

sudo: true

language: python

cache:
  - pip

matrix:
  fast_finish: true
  include:
    - python: 2.7
    - python: 3.6
    - python: 3.7
      dist: xenial

before_install:
  - travis_retry pip install --upgrade pip setuptools py
  - travis_retry pip install twine wheel coveralls

install:
  - travis_retry pip install -e .[all]

script:
  - ./run-tests.sh

after_success:
  - coveralls
